export const termsFr = [
['1. Accord et organisateur','Les présentes conditions s’appliquent aux billets vendus sur le site officiel Project ISKRA et à la participation aux événements Project ISKRA au Québec. L’organisateur indiqué dans votre confirmation de commande est le commerçant responsable de votre billet. En passant commande, vous acceptez ces conditions et les détails de l’événement présentés avant le paiement.'],
['2. Âge et pièce d’identité','Sauf indication contraire sur la page de l’événement, les soirées Project ISKRA sont réservées aux personnes de 18 ans ou plus. Une pièce d’identité officielle avec photo peut être vérifiée à l’entrée. Un billet ne dispense pas de respecter les restrictions d’âge du lieu ni les conditions de son permis d’alcool.'],
['3. Prix et paiement','Les prix sont en dollars canadiens. Le type et le nombre de billets, les taxes applicables, les frais obligatoires, le prix total, la date, l’heure et le lieu sont présentés avant le paiement. Stripe traite les paiements de façon sécurisée. Project ISKRA ne conserve pas les numéros complets de carte de paiement.'],
['4. Livraison et utilisation des billets','Après confirmation du paiement, les billets QR apparaissent dans Mes billets et sont envoyés au courriel de l’acheteur. Chaque code QR permet une seule entrée pour une personne et devient invalide après validation. Gardez vos codes privés. Les billets dupliqués, modifiés, obtenus frauduleusement ou déjà utilisés peuvent être refusés. Contactez-nous rapidement en cas de problème de livraison.'],
['5. Transfert et revente','Un billet peut être donné à une autre personne admissible, sauf si la page de l’événement indique qu’il est nominatif. La revente commerciale, la revente au-delà du prix autorisé, les achats automatisés et le courtage non autorisé sont interdits. Nous pouvons demander à l’acheteur de vérifier une commande en cas de soupçon raisonnable de fraude.'],
['6. Remboursement, annulation et report','Sauf disposition contraire des présentes conditions, de la fiche de l’événement ou de la loi, les ventes de billets sont définitives. Si Project ISKRA annule un événement, l’acheteur sera informé dès que raisonnablement possible et le prix du billet ainsi que les frais obligatoires seront remboursés sur le mode de paiement d’origine. Si l’événement est reporté ou si son horaire ou son lieu change de façon importante, le billet demeure valide et l’organisateur communiquera les options disponibles. Ces conditions ne limitent aucun droit d’annulation, de remboursement ou de rétrofacturation prévu par le droit québécois de la consommation.'],
['7. Entrée et conduite','L’entrée demeure soumise à la capacité, aux exigences de sécurité et aux règles légales du lieu. Les invités doivent suivre les consignes raisonnables du personnel et de la sécurité. Le harcèlement, la violence, les menaces, les armes, les substances illégales, les comportements dangereux et l’intoxication grave sont interdits. Une personne peut être expulsée ou se voir refuser l’entrée pour un motif réel de sécurité, de légalité ou de conduite grave. Cette clause ne supprime aucun recours qui ne peut être légalement exclu.'],
['8. Modifications du programme','Les artistes, les animateurs, les activités et leur ordre peuvent changer. Project ISKRA communiquera les modifications importantes dès que raisonnablement possible. Une modification mineure de programmation ou d’horaire n’annule pas automatiquement un billet; les droits prévus par la loi demeurent applicables.'],
['9. Photographie et enregistrement','Les événements peuvent être photographiés ou enregistrés à des fins de documentation et de promotion. Des avis peuvent être affichés sur place. Les invités souhaitant un accommodement raisonnable concernant leur vie privée doivent contacter l’équipe avant l’événement ou le personnel à leur arrivée. Toute utilisation commerciale ciblée de l’image d’une personne fera l’objet du consentement exigé par la loi.'],
['10. Accessibilité et accommodements','L’accessibilité varie selon le lieu. Contactez l’équipe avant l’achat ou la visite si vous avez besoin d’un accès sans marche, d’une place assise, d’un soutien à la communication ou d’un autre accommodement. Nous fournirons des renseignements exacts et chercherons de bonne foi des arrangements raisonnables.'],
['11. Renseignements personnels','Les renseignements de commande et de présence servent au paiement, à l’émission et à la validation des billets, à la prévention de la fraude, à l’assistance et aux obligations légales. Les messages promotionnels nécessitent le consentement applicable et comprennent un moyen de désabonnement. Les renseignements personnels ne sont conservés que pour des besoins opérationnels et légaux légitimes et ne sont pas vendus.'],
['12. Responsabilité et droit applicable','Les invités demeurent responsables de leurs biens et de leurs choix. Dans la mesure permise par la loi, l’organisateur n’est pas responsable des pertes causées uniquement par un invité, un tiers indépendant ou un événement hors de son contrôle raisonnable. Aucune disposition n’exclut une responsabilité ou un droit du consommateur qui ne peut légalement l’être. Ces conditions sont régies par les lois applicables au Québec. Tout litige peut être porté devant un tribunal ou une autorité compétente selon ces lois.']
];
