import {useEffect,useState} from 'react';
import {api,savedTickets} from '../api.js';
import Logo from '../components/Logo.jsx';
import LanguageSwitcher from '../components/LanguageSwitcher.jsx';
import {useToast} from '../components/Toasts.jsx';
import {useI18n} from '../i18n.jsx';
import {money} from '../utils.js';

const COPY={
  en:{welcome:'Your night, in one place.',lead:'Tickets, member offers and the next ISKRA signal. Built for the people inside the room.',login:'Sign in',register:'Create account',email:'Email address',password:'Password',name:'Your name',forgot:'Forgot password?',join:'Join the circle',noAccount:'New to ISKRA?',hasAccount:'Already a member?',verifySent:'Check your email. Your private verification link is on its way.',forgotCopy:'Enter your email. If an account exists, we will send a secure reset link.',sendReset:'Send reset link',back:'Back to sign in',reset:'Choose new password',savePassword:'Save new password',overview:'Overview',tickets:'My tickets',orders:'Orders',events:'Events',offers:'Offers',membership:'Membership',preferences:'Preferences',security:'Profile & security',support:'Support',signout:'Sign out',hello:'Good to see you',accountHome:'Your ISKRA account',activeTickets:'Active tickets',totalOrders:'Orders',savedEvents:'Saved events',memberState:'Membership',next:'Next event',viewTicket:'Your door pass',noTickets:'No account tickets yet.',noTicketsCopy:'Buy with this email or claim tickets saved on this device.',browse:'Browse events',noOrders:'No orders yet.',saveEvent:'Save event',saved:'Saved',circle:'ISKRA Circle',circleCopy:'Member-first ticket windows, private offers and priority event signals.',manageBilling:'Manage billing',joinMembership:'Join membership',newsletter:'Promotional letters',reminders:'Event reminders',offerEmails:'Member offers',updates:'Product updates',savePrefs:'Save preferences',profile:'Profile details',saveProfile:'Save profile',verified:'Verified email',unverified:'Email verification pending',delete:'Delete account',deleteCopy:'This permanently closes your account. Ticket and financial records are retained only where legally required.',confirmPassword:'Confirm password',deleteAction:'Permanently delete',help:'Need the team?',helpCopy:'Ticket transfers, event access, memberships and account recovery are handled by the ISKRA team.',contact:'Contact support',publicSite:'Public website'},
  uk:{welcome:'Ваша ніч — в одному місці.',lead:'Квитки, пропозиції для учасників і наступний сигнал ISKRA. Створено для людей у залі.',login:'Увійти',register:'Створити акаунт',email:'Електронна пошта',password:'Пароль',name:'Ваше імʼя',forgot:'Забули пароль?',join:'Приєднатися',noAccount:'Вперше в ISKRA?',hasAccount:'Вже маєте акаунт?',verifySent:'Перевірте пошту. Приватне посилання для підтвердження вже в дорозі.',forgotCopy:'Введіть email. Якщо акаунт існує, ми надішлемо захищене посилання.',sendReset:'Надіслати посилання',back:'Назад до входу',reset:'Створіть новий пароль',savePassword:'Зберегти пароль',overview:'Огляд',tickets:'Мої квитки',orders:'Замовлення',events:'Події',offers:'Пропозиції',membership:'Участь',preferences:'Налаштування',security:'Профіль і безпека',support:'Підтримка',signout:'Вийти',hello:'Раді бачити',accountHome:'Ваш акаунт ISKRA',activeTickets:'Активні квитки',totalOrders:'Замовлення',savedEvents:'Збережені події',memberState:'Участь',next:'Наступна подія',viewTicket:'Ваш пропуск',noTickets:'У акаунті ще немає квитків.',noTicketsCopy:'Купуйте з цим email або додайте квитки з цього пристрою.',browse:'Переглянути події',noOrders:'Замовлень ще немає.',saveEvent:'Зберегти',saved:'Збережено',circle:'ISKRA Circle',circleCopy:'Ранній доступ до квитків, приватні пропозиції та сигнали про події.',manageBilling:'Керувати оплатою',joinMembership:'Приєднатися',newsletter:'Промолисти',reminders:'Нагадування про події',offerEmails:'Пропозиції учасникам',updates:'Оновлення продукту',savePrefs:'Зберегти',profile:'Дані профілю',saveProfile:'Зберегти профіль',verified:'Email підтверджено',unverified:'Email очікує підтвердження',delete:'Видалити акаунт',deleteCopy:'Ця дія назавжди закриє акаунт. Фінансові записи зберігаються лише у випадках, передбачених законом.',confirmPassword:'Підтвердіть пароль',deleteAction:'Видалити назавжди',help:'Потрібна команда?',helpCopy:'Перенесення квитків, доступ, участь і відновлення акаунта вирішує команда ISKRA.',contact:'Написати підтримці',publicSite:'Публічний сайт'},
  ru:{welcome:'Ваша ночь — в одном месте.',lead:'Билеты, предложения для участников и следующий сигнал ISKRA. Создано для людей в зале.',login:'Войти',register:'Создать аккаунт',email:'Электронная почта',password:'Пароль',name:'Ваше имя',forgot:'Забыли пароль?',join:'Присоединиться',noAccount:'Впервые в ISKRA?',hasAccount:'Уже есть аккаунт?',verifySent:'Проверьте почту. Приватная ссылка для подтверждения уже отправлена.',forgotCopy:'Введите email. Если аккаунт существует, мы отправим защищенную ссылку.',sendReset:'Отправить ссылку',back:'Назад ко входу',reset:'Создайте новый пароль',savePassword:'Сохранить пароль',overview:'Обзор',tickets:'Мои билеты',orders:'Заказы',events:'События',offers:'Предложения',membership:'Участие',preferences:'Настройки',security:'Профиль и безопасность',support:'Поддержка',signout:'Выйти',hello:'Рады видеть',accountHome:'Ваш аккаунт ISKRA',activeTickets:'Активные билеты',totalOrders:'Заказы',savedEvents:'Сохраненные события',memberState:'Участие',next:'Следующее событие',viewTicket:'Ваш пропуск',noTickets:'В аккаунте пока нет билетов.',noTicketsCopy:'Покупайте с этим email или добавьте билеты с этого устройства.',browse:'Смотреть события',noOrders:'Заказов пока нет.',saveEvent:'Сохранить',saved:'Сохранено',circle:'ISKRA Circle',circleCopy:'Ранний доступ к билетам, приватные предложения и сигналы о событиях.',manageBilling:'Управлять оплатой',joinMembership:'Присоединиться',newsletter:'Промописьма',reminders:'Напоминания о событиях',offerEmails:'Предложения участникам',updates:'Обновления продукта',savePrefs:'Сохранить',profile:'Данные профиля',saveProfile:'Сохранить профиль',verified:'Email подтвержден',unverified:'Email ожидает подтверждения',delete:'Удалить аккаунт',deleteCopy:'Это навсегда закроет аккаунт. Финансовые записи сохраняются только когда этого требует закон.',confirmPassword:'Подтвердите пароль',deleteAction:'Удалить навсегда',help:'Нужна команда?',helpCopy:'Перенос билетов, доступ, участие и восстановление аккаунта решает команда ISKRA.',contact:'Написать поддержке',publicSite:'Публичный сайт'}
};
const NAV=['overview','tickets','orders','events','offers','membership','preferences','security','support'];
const statusClass=value=>`account-status ${String(value||'inactive').replaceAll('_','-')}`;

export default function AccountPage(){
  const {language}=useI18n();const c=COPY[language]||COPY.en;const toast=useToast();
  const [auth,setAuth]=useState(null);const [data,setData]=useState(null);const [loading,setLoading]=useState(true);
  const [mode,setMode]=useState('login');const [section,setSection]=useState(()=>location.hash.slice(1)||'overview');
  const [form,setForm]=useState({name:'',email:'',password:'',newsletter:false});const [notice,setNotice]=useState('');
  const [profile,setProfile]=useState({name:'',locale:language});const [preferences,setPreferences]=useState({});const [deletePassword,setDeletePassword]=useState('');
  const load=async()=>{try{const me=await api.accountMe();setAuth(me);const overview=await api.accountOverview();setData(overview);setProfile({name:me.user.name,locale:me.user.locale});setPreferences(me.user.preferences||{});const local=savedTickets();if(local.length){const result=await api.accountClaimTickets(me.csrfToken,local);if(result.claimed){setData(await api.accountOverview());}}}catch{setAuth(null);setData(null);}finally{setLoading(false);}};
  useEffect(()=>{const params=new URLSearchParams(location.search);const verify=params.get('verify');const reset=params.get('reset');if(reset){setMode('reset');setLoading(false);return;}if(verify){api.accountVerify(verify).then(result=>{setAuth(result);history.replaceState({},'',location.pathname);return load();}).catch(error=>{setNotice(error.message);setLoading(false);});return;}load();},[]);
  useEffect(()=>{const handler=()=>setSection(location.hash.slice(1)||'overview');addEventListener('hashchange',handler);return()=>removeEventListener('hashchange',handler);},[]);
  const submitAuth=async e=>{e.preventDefault();setNotice('');try{if(mode==='login'){const result=await api.accountLogin({email:form.email,password:form.password});setAuth(result);await load();}else if(mode==='register'){const result=await api.accountRegister({...form,locale:language});const source=localStorage.getItem('iskra_campaign_source');if(source){api.campaignRecord(source,'convert').catch(()=>{});localStorage.removeItem('iskra_campaign_source');}setNotice(result.message||c.verifySent);}else if(mode==='forgot'){const result=await api.accountForgot(form.email);setNotice(result.message);}else if(mode==='reset'){const token=new URLSearchParams(location.search).get('reset');await api.accountReset(token,form.password);history.replaceState({},'',location.pathname);setMode('login');setNotice('Password updated. Sign in with your new password.');}}catch(error){setNotice(error.message);}};
  const signout=async()=>{try{await api.accountLogout(auth.csrfToken);}finally{setAuth(null);setData(null);}};
  const refresh=async()=>setData(await api.accountOverview());
  if(loading)return <main className="account-loading"><Logo/><span>Connecting your ISKRA account…</span></main>;
  if(!auth||!data)return <AuthExperience c={c} language={language} mode={mode} setMode={setMode} form={form} setForm={setForm} submit={submitAuth} notice={notice}/>;
  const activeTickets=data.tickets.filter(ticket=>ticket.admissionValid!==false&&ticket.status==='reserved'&&new Date(ticket.eventDate)>new Date());
  const upcoming=data.events.filter(event=>new Date(event.date)>new Date());
  return <main className="account-app">
    <aside className="account-rail"><a className="account-logo" href="/"><Logo/>ISKRA</a><div className="account-member"><span>{c.hello}</span><b>{auth.user.name}</b><small>{auth.user.email}</small></div><nav>{NAV.map(id=><a key={id} href={`#${id}`} className={section===id?'active':''}>{c[id]}</a>)}</nav><button onClick={signout}>{c.signout} →</button></aside>
    <div className="account-main"><header className="account-top"><a href="/">← {c.publicSite}</a><LanguageSwitcher/><button onClick={signout}>{c.signout}</button></header><nav className="account-mobile-nav">{NAV.map(id=><a key={id} href={`#${id}`} className={section===id?'active':''}>{c[id]}</a>)}</nav>
      <div className="account-content">
        {section==='overview'&&<Overview c={c} user={auth.user} tickets={activeTickets} orders={data.orders} events={upcoming} membership={data.membership}/>} 
        {section==='tickets'&&<TicketWallet c={c} tickets={data.tickets}/>} 
        {section==='orders'&&<Orders c={c} orders={data.orders}/>} 
        {section==='events'&&<AccountEvents c={c} events={data.events} save={async slug=>{await api.accountSaveEvent(auth.csrfToken,slug);await refresh();}}/>} 
        {section==='offers'&&<Offers c={c}/>} 
        {section==='membership'&&<Membership c={c} membership={data.membership} action={async()=>{try{const active=!['inactive','canceled','cancelled'].includes(data.membership.status);const result=active?await api.membershipPortal(auth.csrfToken):await api.membershipCheckout(auth.csrfToken);location.assign(result.url||result.checkoutUrl);}catch(error){toast(error.message,'!');}}}/>} 
        {section==='preferences'&&<Preferences c={c} value={preferences} setValue={setPreferences} save={async()=>{const result=await api.accountPreferences(auth.csrfToken,preferences);setPreferences(result.preferences);toast('Preferences saved.','OK');}}/>} 
        {section==='security'&&<Security c={c} user={auth.user} profile={profile} setProfile={setProfile} save={async()=>{const result=await api.accountProfile(auth.csrfToken,profile);setAuth({...auth,user:result.user});toast('Profile updated.','OK');}} deletePassword={deletePassword} setDeletePassword={setDeletePassword} remove={async()=>{if(!confirm('Permanently delete this account?'))return;await api.accountDelete(auth.csrfToken,deletePassword);setAuth(null);setData(null);}}/>} 
        {section==='support'&&<Support c={c}/>} 
      </div>
    </div>
  </main>;
}

function AuthExperience({c,language,mode,setMode,form,setForm,submit,notice}){return <main className="account-auth"><section className="account-auth-story"><a href="/" className="account-logo"><Logo/>ISKRA</a><div><p>PROJECT ISKRA / MONTRÉAL</p><h1>{c.welcome}</h1><span>{c.lead}</span></div><figure><img src="/last-event/project_iskra_event 18.jpg" alt="Guests at a Project ISKRA night"/></figure></section><section className="account-auth-form"><div className="account-auth-tools"><LanguageSwitcher/><a href="/">×</a></div><form onSubmit={submit}><span className="account-kicker">{mode==='register'?c.join:mode==='forgot'?c.forgot:mode==='reset'?c.reset:c.login}</span><h2>{mode==='register'?c.register:mode==='forgot'?c.forgot:mode==='reset'?c.reset:c.login}</h2>{mode==='forgot'&&<p>{c.forgotCopy}</p>}{mode==='register'&&<label><span>{c.name}</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} autoComplete="name" required/></label>} {mode!=='reset'&&<label><span>{c.email}</span><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} autoComplete="email" required/></label>}{!['forgot'].includes(mode)&&<label><span>{c.password}</span><input type="password" minLength="10" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} autoComplete={mode==='login'?'current-password':'new-password'} required/></label>}{mode==='register'&&<label className="account-consent"><input type="checkbox" checked={form.newsletter} onChange={e=>setForm({...form,newsletter:e.target.checked})}/><span>Send me event announcements and member offers. Optional, unsubscribe anytime.</span></label>}{notice&&<div className="account-notice" role="status">{notice}</div>}<button className="btn btn-primary">{mode==='register'?c.register:mode==='forgot'?c.sendReset:mode==='reset'?c.savePassword:c.login}</button>{mode==='login'&&<button type="button" className="account-link" onClick={()=>setMode('forgot')}>{c.forgot}</button>}<footer>{mode==='login'?c.noAccount:c.hasAccount} <button type="button" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?c.register:c.back}</button></footer></form><small className="account-auth-locale">{language.toUpperCase()} · Secure account access</small></section></main>}
function PageTitle({kicker,title,copy}){return <header className="account-page-title"><p>{kicker}</p><h1>{title}</h1>{copy&&<span>{copy}</span>}</header>}
function Overview({c,user,tickets,orders,events,membership}){return <><PageTitle kicker={c.hello} title={`${user.name}.`} copy={c.accountHome}/><section className="account-metrics"><article><span>{c.activeTickets}</span><b>{tickets.length}</b><a href="#tickets">Open wallet →</a></article><article><span>{c.totalOrders}</span><b>{orders.length}</b><a href="#orders">View history →</a></article><article><span>{c.savedEvents}</span><b>{events.filter(e=>e.saved).length}</b><a href="#events">Your nights →</a></article><article><span>{c.memberState}</span><b className="account-word-metric">{membership.status}</b><a href="#membership">View plan →</a></article></section><section className="account-feature"><div><p>{c.next}</p><h2>{events[0]?.title||'The next spark is loading.'}</h2><span>{events[0]?new Date(events[0].date).toLocaleString():c.lead}</span><a className="btn btn-primary" href="#events">{c.browse}</a></div><img src={events[0]?.image||'/last-event/project_iskra_event 6.jpg'} alt="Project ISKRA event"/></section></>}
function TicketWallet({c,tickets}){return <><PageTitle kicker="Account / door" title={c.tickets} copy={c.viewTicket}/>{!tickets.length?<EmptyAccount title={c.noTickets} copy={c.noTicketsCopy} href="/schedule" action={c.browse}/>:<div className="account-ticket-grid">{tickets.map(ticket=><article key={ticket.reference} className={ticket.status}><header><span className={statusClass(ticket.status)}>{ticket.admissionValid===false?'table reservation':ticket.status}</span><code>{ticket.reference}</code></header><img src={ticket.qrDataUrl} alt={`QR ${ticket.reference}`}/><div><p>{new Date(ticket.eventDate).toLocaleDateString()}</p><h2>{ticket.eventTitle}</h2><span>{ticket.room} · {ticket.tier}</span>{ticket.admissionValid===false&&<span className="wallet-admission-warning">Not valid for entry. Separate admission QR required.</span>}<footer><b>{ticket.buyerName}</b><strong>{money(ticket.price)}</strong></footer></div></article>)}</div>}</>}
function Orders({c,orders}){return <><PageTitle kicker="Account / commerce" title={c.orders}/>{!orders.length?<EmptyAccount title={c.noOrders} copy={c.noTicketsCopy} href="/schedule" action={c.browse}/>:<div className="account-orders"><div className="account-order-head"><span>Order</span><span>Event</span><span>Payment</span><span>Total</span></div>{orders.map(order=><article key={order.id}><div><b>#{String(order.id).slice(-8).toUpperCase()}</b><small>{new Date(order.createdAt).toLocaleDateString()}</small></div><div><b>{order.eventSlug}</b><small>{order.qty} × {order.tier}</small></div><span className={statusClass(order.paymentStatus)}>{order.paymentStatus}</span><strong>{money(order.total)}</strong></article>)}</div>}</>}
function AccountEvents({c,events,save}){return <><PageTitle kicker="Account / calendar" title={c.events}/><div className="account-event-grid">{events.map(event=><article key={event.slug}><img src={event.image||'/last-event/project_iskra_event 14.jpg'} alt=""/><div><p>{new Date(event.date).toLocaleDateString()}</p><h2>{event.title}</h2><span>{event.room} · {money(event.from)}</span><button onClick={()=>save(event.slug)}>{event.saved?`✓ ${c.saved}`:`+ ${c.saveEvent}`}</button></div></article>)}</div></>}
function Offers({c}){const [campaigns,setCampaigns]=useState([]);useEffect(()=>{api.promoPublic().then(r=>setCampaigns(r.campaigns||[])).catch(()=>{});},[]);return <><PageTitle kicker="Account / access" title={c.offers}/><div className="account-offers">{campaigns.map(item=><article key={item.code}><span className={statusClass(item.status)}>{item.status}</span><h2>{item.code}</h2><p>{item.label}</p><b>{item.percentOff?`${item.percentOff}% OFF`:money(item.flatPrice)}</b><a href="/schedule">Use at checkout →</a></article>)}</div></>}
function Membership({c,membership,action}){const active=!['inactive','canceled','cancelled'].includes(membership.status);return <><PageTitle kicker="Account / membership" title={c.circle}/><section className="account-membership"><div><span className={statusClass(membership.status)}>{membership.status}</span><h2>STAY CLOSE<br/>TO THE SPARK.</h2><p>{c.circleCopy}</p><button className="btn btn-primary" onClick={action}>{active?c.manageBilling:c.joinMembership}</button></div><ol><li><b>01</b><span>Member-first ticket windows</span></li><li><b>02</b><span>Private group and birthday offers</span></li><li><b>03</b><span>Priority lineup and venue signals</span></li></ol></section></>}
function Preferences({c,value,setValue,save}){const fields=[['newsletter',c.newsletter],['eventReminders',c.reminders],['offers',c.offerEmails],['productUpdates',c.updates]];return <><PageTitle kicker="Account / consent" title={c.preferences}/><section className="account-settings-card">{fields.map(([key,label])=><label className="account-switch" key={key}><span><b>{label}</b><small>You can change this at any time.</small></span><input type="checkbox" checked={Boolean(value[key])} onChange={e=>setValue({...value,[key]:e.target.checked})}/></label>)}<button className="btn btn-primary" onClick={save}>{c.savePrefs}</button></section></>}
function Security({c,user,profile,setProfile,save,deletePassword,setDeletePassword,remove}){return <><PageTitle kicker="Account / identity" title={c.security}/><div className="account-settings-grid"><section className="account-settings-card"><h2>{c.profile}</h2><label><span>{c.name}</span><input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label><span>{c.email}</span><input value={user.email} disabled/></label><p className={statusClass(user.emailVerified?'active':'pending')}>{user.emailVerified?c.verified:c.unverified}</p><button className="btn btn-primary" onClick={save}>{c.saveProfile}</button></section><section className="account-settings-card account-danger"><h2>{c.delete}</h2><p>{c.deleteCopy}</p><label><span>{c.confirmPassword}</span><input type="password" value={deletePassword} onChange={e=>setDeletePassword(e.target.value)}/></label><button onClick={remove}>{c.deleteAction}</button></section></div></>}
function Support({c}){return <><PageTitle kicker="Account / support" title={c.help}/><section className="account-support"><h2>THE TEAM IS<br/>ON THE OTHER SIDE.</h2><p>{c.helpCopy}</p><a className="btn btn-primary" href="/contact">{c.contact}</a><div><span>General</span><a href="mailto:hello@projekt-iskra.com">hello@projekt-iskra.com</a></div></section></>}
function EmptyAccount({title,copy,href,action}){return <section className="account-empty"><span>0</span><h2>{title}</h2><p>{copy}</p><a className="btn btn-primary" href={href}>{action}</a></section>}
