const groups={
  identity:{en:'This secure account update was requested for your Project ISKRA profile. Review the details and contact the team if you did not expect it.',uk:'Це захищене оновлення стосується вашого профілю Project ISKRA. Перевірте деталі й напишіть команді, якщо ви цього не очікували.',ru:'Это защищенное обновление относится к вашему профилю Project ISKRA. Проверьте детали и напишите команде, если вы этого не ожидали.'},
  commerce:{en:'This message records an update to your ISKRA order, payment, or ticket. Your account remains the authoritative place to review status.',uk:'Цей лист фіксує оновлення замовлення, оплати або квитка ISKRA. Актуальний статус завжди доступний в акаунті.',ru:'Это письмо фиксирует обновление заказа, оплаты или билета ISKRA. Актуальный статус всегда доступен в аккаунте.'},
  event:{en:'Important information about an ISKRA event connected to your account is included here. Review it before arriving at the venue.',uk:'Тут важлива інформація про подію ISKRA, повʼязану з вашим акаунтом. Перегляньте її перед прибуттям.',ru:'Здесь важная информация о событии ISKRA, связанном с вашим аккаунтом. Просмотрите ее перед прибытием.'},
  marketing:{en:'You are receiving this because of your explicit ISKRA communication preferences. You can change them or unsubscribe at any time.',uk:'Ви отримали цей лист відповідно до налаштувань комунікації ISKRA. Їх можна змінити або скасувати будь-коли.',ru:'Вы получили это письмо согласно настройкам коммуникации ISKRA. Их можно изменить или отменить в любое время.'},
  membership:{en:'This is an update to your ISKRA Circle membership. Billing status comes directly from Stripe and can be managed securely in your account.',uk:'Це оновлення участі в ISKRA Circle. Статус оплати надходить зі Stripe й безпечно керується в акаунті.',ru:'Это обновление участия в ISKRA Circle. Статус оплаты поступает из Stripe и безопасно управляется в аккаунте.'}
};
const rows=[
['welcome','identity','Welcome to Project ISKRA','Вітаємо у Project ISKRA','Добро пожаловать в Project ISKRA'],
['verification','identity','Verify your email','Підтвердьте email','Подтвердите email'],
['magic-link','identity','Your secure sign-in link','Захищене посилання для входу','Защищенная ссылка для входа'],
['password-reset','identity','Reset your password','Скиньте пароль','Сбросьте пароль'],
['password-changed','identity','Your password changed','Ваш пароль змінено','Ваш пароль изменен'],
['email-changed','identity','Your email changed','Ваш email змінено','Ваш email изменен'],
['login-alert','identity','New account sign-in','Новий вхід в акаунт','Новый вход в аккаунт'],
['new-device','identity','New device connected','Підʼєднано новий пристрій','Подключено новое устройство'],
['account-recovery','identity','Account recovery update','Оновлення відновлення акаунта','Обновление восстановления аккаунта'],
['account-deletion','identity','Account deletion confirmed','Видалення акаунта підтверджено','Удаление аккаунта подтверждено'],
['order-receipt','commerce','Your ISKRA receipt','Ваш чек ISKRA','Ваш чек ISKRA'],
['payment-pending','commerce','Payment is processing','Оплата обробляється','Оплата обрабатывается'],
['payment-confirmed','commerce','Payment confirmed','Оплату підтверджено','Оплата подтверждена'],
['payment-failed','commerce','Payment needs attention','Оплата потребує уваги','Оплата требует внимания'],
['ticket-issued','commerce','Your ISKRA ticket','Ваш квиток ISKRA','Ваш билет ISKRA'],
['multi-ticket-delivery','commerce','Your group tickets','Квитки для вашої групи','Билеты для вашей группы'],
['ticket-resend','commerce','Your tickets, sent again','Ваші квитки надіслано повторно','Ваши билеты отправлены повторно'],
['ticket-transfer-sent','commerce','Ticket transfer started','Перенесення квитка розпочато','Перенос билета начат'],
['ticket-transfer-accepted','commerce','Ticket transfer complete','Перенесення квитка завершено','Перенос билета завершен'],
['refund-confirmed','commerce','Refund confirmed','Повернення підтверджено','Возврат подтвержден'],
['event-reminder','event','Your ISKRA night is close','Ваша ніч ISKRA вже близько','Ваша ночь ISKRA уже близко'],
['event-today','event','ISKRA is tonight','ISKRA вже сьогодні','ISKRA уже сегодня'],
['doors-open','event','Doors are open','Двері відчинено','Двери открыты'],
['event-updated','event','Event details updated','Деталі події оновлено','Детали события обновлены'],
['venue-changed','event','Venue change','Зміна локації','Смена площадки'],
['event-postponed','event','Event postponed','Подію перенесено','Событие перенесено'],
['event-cancelled','event','Event cancelled','Подію скасовано','Событие отменено'],
['waitlist-joined','event','You joined the waitlist','Ви у списку очікування','Вы в списке ожидания'],
['waitlist-available','event','A ticket is available','Квиток доступний','Билет доступен'],
['post-event-thanks','event','Thank you for the night','Дякуємо за цю ніч','Спасибо за эту ночь'],
['newsletter-welcome','marketing','You are on the ISKRA list','Ви у списку ISKRA','Вы в списке ISKRA'],
['presale-access','marketing','Your presale window is open','Ваш передпродаж відкрито','Ваша предпродажа открыта'],
['lineup-announcement','marketing','The lineup has landed','Лайнап оголошено','Лайнап объявлен'],
['new-event','marketing','A new ISKRA night','Нова ніч ISKRA','Новая ночь ISKRA'],
['saved-event-reminder','marketing','An event you saved is moving','Збережена подія наближається','Сохраненное событие приближается'],
['personalized-offer','marketing','An offer selected for you','Пропозиція для вас','Предложение для вас'],
['promo-expiring','marketing','Your offer ends soon','Ваша пропозиція скоро завершиться','Ваше предложение скоро завершится'],
['birthday-offer','marketing','A birthday night from ISKRA','Святкова ніч від ISKRA','Праздничная ночь от ISKRA'],
['abandoned-checkout','marketing','Your ticket selection is waiting','Ваш вибір квитків очікує','Ваш выбор билетов ожидает'],
['inactive-return','marketing','The room remembers you','Зала памʼятає вас','Зал помнит вас'],
['membership-welcome','membership','Welcome to ISKRA Circle','Вітаємо в ISKRA Circle','Добро пожаловать в ISKRA Circle'],
['renewal-reminder','membership','Membership renewal reminder','Нагадування про поновлення','Напоминание о продлении'],
['membership-payment-retry','membership','Membership payment needs attention','Оплата участі потребує уваги','Оплата участия требует внимания'],
['renewal-success','membership','Membership renewed','Участь поновлено','Участие продлено'],
['plan-changed','membership','Membership plan updated','План участі оновлено','План участия обновлен'],
['pause-confirmed','membership','Membership pause confirmed','Паузу участі підтверджено','Пауза участия подтверждена'],
['cancellation-started','membership','Membership cancellation scheduled','Скасування участі заплановано','Отмена участия запланирована'],
['retention-offer','membership','An optional Circle alternative','Альтернатива для Circle','Альтернатива для Circle'],
['cancellation-confirmed','membership','Membership cancellation confirmed','Скасування участі підтверджено','Отмена участия подтверждена'],
['membership-expired','membership','Membership ended','Участь завершено','Участие завершено']
];
export const EMAIL_TEMPLATES=Object.fromEntries(rows.map(([key,group,en,uk,ru])=>[key,{group,en:{subject:en,headline:en,body:groups[group].en},uk:{subject:uk,headline:uk,body:groups[group].uk},ru:{subject:ru,headline:ru,body:groups[group].ru}}]));
export const emailTemplate=(key,locale='en')=>EMAIL_TEMPLATES[key]?.[locale]||EMAIL_TEMPLATES[key]?.en||null;
