import {useEffect,useState} from 'react';
import {api} from '../api.js';
import {useToast} from './Toasts.jsx';

const initial=(events=[])=>({eventSlug:events[0]?.slug||'',customerName:'',customerEmail:'',restrictEmail:false,
  title:'Private ISKRA order',description:'',admission:{tierKey:'general',qty:1,unitPrice:events[0]?.from||25,discount:{type:'none',value:0}},
  vip:{qty:0,unitPrice:140,discount:{type:'none',value:0},inclusions:'Bottle 20% off',reservationMode:'checkout'},
  allowPromoStacking:false,internalNotes:'',expiresAt:'',maxRedemptions:1});
const money=value=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(Number(value)||0);
const date=value=>value?new Date(value).toLocaleString():'Never';
const copySafely=async value=>{
  if(!navigator.clipboard?.writeText) return false;
  try{
    await navigator.clipboard.writeText(value);
    return true;
  }catch{
    return false;
  }
};

export default function CustomOrdersWorkspace({events=[]}){
  const toast=useToast();const [form,setForm]=useState(()=>initial(events));const [editing,setEditing]=useState(null);
  const [rows,setRows]=useState([]);const [page,setPage]=useState({page:1,pages:1,total:0});const [query,setQuery]=useState('');const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);const [audit,setAudit]=useState(null);
  const load=async(value=1)=>{try{const result=await api.adminCustomOrders(value,query,status);setRows(result.items);setPage(result.pagination);}catch(error){toast(error.message,'!');}};
  useEffect(()=>{load();},[]); // eslint-disable-line
  const nested=(section,key,value)=>setForm(current=>({...current,[section]:{...current[section],[key]:value}}));
  const discount=(section,key,value)=>setForm(current=>({...current,[section]:{...current[section],discount:{...current[section].discount,[key]:value}}}));
  const payload=()=>({...form,expiresAt:form.expiresAt||null,maxRedemptions:Number(form.maxRedemptions),
    admission:{...form.admission,qty:Number(form.admission.qty),unitPrice:Number(form.admission.unitPrice),discount:{...form.admission.discount,value:Number(form.admission.discount.value)}},
    vip:{...form.vip,qty:Number(form.vip.qty),unitPrice:Number(form.vip.unitPrice),discount:{...form.vip.discount,value:Number(form.vip.discount.value)},inclusions:String(form.vip.inclusions).split('\n').map(v=>v.trim()).filter(Boolean)}});
  const save=async event=>{event.preventDefault();setBusy(true);try{const result=editing?await api.adminUpdateCustomOrder(editing,payload()):await api.adminCreateCustomOrder(payload());const copied=result.code?await copySafely(result.code):false;toast(editing?'Custom order updated.':copied?'Custom order created and code copied.':'Custom order created. Clipboard access was blocked, but the code was saved.','OK');setEditing(null);setForm(initial(events));await load();}catch(error){toast(error.message,'!');}finally{setBusy(false);}};
  const edit=row=>{setEditing(row.id);setForm({eventSlug:row.eventSlug,customerName:row.customerName||'',customerEmail:row.customerEmail||'',restrictEmail:row.restrictEmail,title:row.title,description:row.description||'',admission:{...row.admission,discount:{...row.admission.discount}},vip:{...row.vip,discount:{...row.vip.discount},inclusions:(row.vip.inclusions||[]).join('\n')},allowPromoStacking:row.allowPromoStacking,internalNotes:row.internalNotes||'',expiresAt:row.expiresAt?new Date(row.expiresAt).toISOString().slice(0,16):'',maxRedemptions:row.maxRedemptions});document.getElementById('custom-order-editor')?.scrollIntoView({behavior:'smooth'});};
  const action=async(fn,message)=>{setBusy(true);try{const result=await fn();const copied=result?.code?await copySafely(result.code):false;toast(copied?message:`${message} Clipboard access was blocked.`,copied?'OK':'!');await load(page.page);}catch(error){toast(error.message,'!');}finally{setBusy(false);}};
  const copy=async value=>{toast(await copySafely(value)?'Copied.':'Clipboard access was blocked.','OK');};
  return <div className="custom-orders-admin"><form id="custom-order-editor" className="admin-surface admin-form custom-order-editor" onSubmit={save}>
    <div className="admin-section-title"><div><span>Private checkout builder</span><h2>{editing?'Edit custom order':'Create custom order'}</h2></div>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(initial(events));}}>Cancel edit</button>}</div>
    <div className="admin-field-grid"><label><span>Event *</span><select required value={form.eventSlug} onChange={e=>setForm({...form,eventSlug:e.target.value})}><option value="">Choose event</option>{events.map(row=><option key={row.slug} value={row.slug}>{row.title}</option>)}</select></label><label><span>Customer name</span><input value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})}/></label><label><span>Customer email</span><input type="email" value={form.customerEmail} onChange={e=>setForm({...form,customerEmail:e.target.value})}/></label><label className="admin-toggle"><input type="checkbox" checked={form.restrictEmail} onChange={e=>setForm({...form,restrictEmail:e.target.checked})}/><span><b>Restrict to email</b><small>Reject every other email.</small></span></label></div>
    <div className="admin-field-grid"><label><span>Customer title *</span><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label><span>Expires</span><input type="datetime-local" value={form.expiresAt} onChange={e=>setForm({...form,expiresAt:e.target.value})}/></label><label><span>Max redemptions</span><input type="number" min="1" max="100" value={form.maxRedemptions} onChange={e=>setForm({...form,maxRedemptions:e.target.value})}/></label><label className="admin-toggle"><input type="checkbox" checked={form.allowPromoStacking} onChange={e=>setForm({...form,allowPromoStacking:e.target.checked})}/><span><b>Allow promo stacking</b><small>Admission only, never VIP.</small></span></label></div>
    <label><span>Customer description</span><textarea rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>
    <div className="custom-order-products"><ProductFields title="Admission tickets"><label><span>Tier</span><select value={form.admission.tierKey} onChange={e=>nested('admission','tierKey',e.target.value)}><option value="general">Early bird</option><option value="early">Late bird</option></select></label><NumberField label="Quantity" value={form.admission.qty} max="20" onChange={v=>nested('admission','qty',v)}/><NumberField label="Unit price" value={form.admission.unitPrice} onChange={v=>nested('admission','unitPrice',v)}/><DiscountFields data={form.admission.discount} set={(key,value)=>discount('admission',key,value)}/></ProductFields>
    <ProductFields title="VIP tables"><NumberField label="Quantity" value={form.vip.qty} max="4" onChange={v=>nested('vip','qty',v)}/><NumberField label="Unit price" value={form.vip.unitPrice} onChange={v=>nested('vip','unitPrice',v)}/><DiscountFields data={form.vip.discount} set={(key,value)=>discount('vip',key,value)}/><label><span>Reservation</span><select value={form.vip.reservationMode} onChange={e=>nested('vip','reservationMode',e.target.value)}><option value="checkout">At checkout</option><option value="immediate">Immediately</option></select></label><label className="full"><span>Inclusions, one per line</span><textarea rows="3" value={form.vip.inclusions} onChange={e=>nested('vip','inclusions',e.target.value)}/></label></ProductFields></div>
    <label><span>Internal notes</span><textarea rows="3" value={form.internalNotes} onChange={e=>setForm({...form,internalNotes:e.target.value})}/></label><button className="btn btn-primary" disabled={busy}>{busy?'Saving…':editing?'Save changes':'Create secure order'}</button>
  </form>
  <section className="admin-surface"><div className="admin-section-title"><div><span>Private sales ledger</span><h2>Custom orders</h2></div><b>{page.total||0}</b></div><div className="custom-order-filters"><input type="search" value={query} placeholder="Customer, event, title or code ending" onChange={e=>setQuery(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['active','reserved','redeemed','expired','cancelled'].map(v=><option key={v}>{v}</option>)}</select><button onClick={()=>load()}>Search</button></div><div className="custom-order-list">{rows.map(row=><article key={row.id}><header><div><em className={`admin-status ${row.status}`}>{row.status}</em><h3>{row.title}</h3><p>{row.customerName||'Open customer'} · {row.customerEmail||'Any email'}</p></div><strong>{money(row.pricing.total)}</strong></header><dl><div><dt>Event</dt><dd>{row.eventSlug}</dd></div><div><dt>Package</dt><dd>{row.admission.qty} admission · {row.vip.qty} VIP</dd></div><div><dt>Code</dt><dd><code>••••{row.codeSuffix}</code></dd></div><div><dt>Usage</dt><dd>{row.redemptionCount}/{row.maxRedemptions}</dd></div><div><dt>Expiry</dt><dd>{date(row.expiresAt)}</dd></div></dl><div className="custom-order-actions"><button onClick={()=>copy(row.code)}>Copy code</button><button onClick={()=>copy(`${location.origin}/schedule?event=${encodeURIComponent(row.eventSlug)}&custom_order=${encodeURIComponent(row.code)}`)}>Copy link</button>{['active','draft'].includes(row.status)&&<button onClick={()=>edit(row)}>Edit</button>}<button onClick={()=>action(()=>api.adminDuplicateCustomOrder(row.id),'Duplicated; new code copied.')}>Duplicate</button>{['active','draft'].includes(row.status)&&<button onClick={()=>action(()=>api.adminRegenerateCustomOrder(row.id),'New code copied.')}>New code</button>}{['active','draft'].includes(row.status)&&<button className="danger" onClick={()=>confirm('Cancel this order and release VIP holds?')&&action(()=>api.adminCancelCustomOrder(row.id),'Order cancelled.')}>Cancel</button>}<button onClick={()=>setAudit(audit===row.id?null:row.id)}>Audit</button></div>{audit===row.id&&<ol className="custom-order-audit">{[...(row.audit||[])].reverse().map((item,index)=><li key={index}><b>{item.action.replaceAll('_',' ')}</b><span>{date(item.at)}</span></li>)}</ol>}</article>)}</div>{page.pages>1&&<nav className="admin-pagination"><button disabled={page.page<=1} onClick={()=>load(page.page-1)}>← Previous</button><span>Page {page.page} of {page.pages}</span><button disabled={page.page>=page.pages} onClick={()=>load(page.page+1)}>Next →</button></nav>}</section></div>;
}

function ProductFields({title,children}){return <fieldset><legend>{title}</legend><div className="admin-field-grid">{children}</div></fieldset>}
function NumberField({label,value,onChange,max='100000'}){return <label><span>{label}</span><input type="number" min="0" max={max} step="0.01" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function DiscountFields({data,set}){return <><label><span>Discount</span><select value={data.type} onChange={e=>set('type',e.target.value)}><option value="none">None</option><option value="percent">Percent</option><option value="fixed">Fixed amount</option></select></label><NumberField label="Discount value" value={data.value} max={data.type==='percent'?'100':'100000'} onChange={value=>set('value',value)}/></>}
