import {useEffect,useState} from 'react';
import {api} from '../api.js';
import {useToast} from './Toasts.jsx';

const fresh=()=>({title:'',eventSlug:'',startsAt:'',registrationOpensAt:'',registrationClosesAt:'',checkInClosesAt:'',tableSize:9,startingStack:10000,minimumAge:18,eligibilityRegion:'Quebec, Canada',prizeClaimDeadlineDays:30});
const blockers={LEGAL_NOT_APPROVED:'Legal review is not approved',NO_RULES_VERSION:'Official rules are missing',NO_APPROVAL_TIMESTAMP:'Approval timestamp is missing',NEEDS_THREE_PLACEMENTS:'Configure places 1, 2 and 3',NO_SCHEDULE:'Tournament schedule is incomplete',REGISTRATION_AFTER_START:'Registration must close before start',MUST_BE_FREE:'Entry must remain free'};
const dt=v=>v?new Date(v).toLocaleString([],{dateStyle:'medium',timeStyle:'short'}):'Not set';

export default function PokerAdminWorkspace({events}){
  const toast=useToast();const [list,setList]=useState([]);const [selected,setSelected]=useState(null);const [detail,setDetail]=useState(null);const [form,setForm]=useState(fresh);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const [rules,setRules]=useState({bodyMarkdown:'',reviewer:''});
  const [prizes,setPrizes]=useState([1,2,3].map((placement,index)=>({placement,eventSlug:'',ticketTier:index===0?'VIP':'General admission',ticketQuantity:index===0?2:1,approximateRetailValue:index===0?50:25,currency:'CAD',restrictions:'Non-transferable. Subject to event admission rules.'})));
  const load=async()=>{const rows=await api.adminPokerTournaments();setList(rows);if(selected){const full=await api.adminPokerTournament(selected);setDetail(full);}};
  useEffect(()=>{load().catch(e=>setError(e.message));},[selected]);
  const run=async(work,message)=>{setBusy(true);setError('');try{await work();await load();toast(message,'OK');}catch(e){setError(e.message);}finally{setBusy(false);}};
  const choose=async id=>{setSelected(id);setError('');};
  const create=e=>{e.preventDefault();run(async()=>{const made=await api.adminPokerSave(form);setSelected(made._id);setForm(fresh());},'Tournament draft created.');};
  const setPrize=(i,key,value)=>setPrizes(rows=>rows.map((row,n)=>n===i?{...row,[key]:value}:row));
  const savePrizes=()=>run(()=>api.adminPokerPrizes(selected,prizes),'Prize package saved.');
  const lifecycle=(action,label,confirmText)=>{if(confirmText&&!window.confirm(confirmText))return;run(()=>api.adminPokerAction(selected,action,action==='cancel'?{reason:'Cancelled by operations'}:{}),label);};
  const selectedRow=list.find(row=>String(row._id)===String(selected));
  return <div className="admin-poker-workspace">
    {error&&<p className="admin-poker-error">{error}</p>}
    <section className="admin-poker-command"><div><span>Compliance boundary</span><h2>Free play only.</h2><p>No buy-ins, paid re-entry, deposits, cash prizes or cash-value chips. Publication remains blocked until a named reviewer approves complete official rules.</p></div><a className="btn btn-ghost" href="/play/poker">View public lobby</a></section>
    <div className="admin-two-column admin-editor-layout"><section className="admin-surface"><div className="admin-section-title"><div><span>Tournament inventory</span><h2>{list.length} tournaments</h2></div></div><div className="admin-poker-list">{list.map(row=><button key={row._id} className={String(row._id)===String(selected)?'active':''} onClick={()=>choose(row._id)}><div><b>{row.title}</b><span>{dt(row.startsAt)}</span></div><em>{row.state.replaceAll('_',' ')}</em><small>{row.registeredCount} registered · {row.publishBlockers.length} blockers</small></button>)}{!list.length&&<p className="admin-form-note">No tournament drafts yet. Create the first one beside this list.</p>}</div></section>
      <form className="admin-surface admin-form" onSubmit={create}><div className="admin-section-title"><div><span>New tournament</span><h2>Create draft</h2></div></div><label><span>Title *</span><input value={form.title} required onChange={e=>setForm({...form,title:e.target.value})}/></label><label><span>Prize event *</span><select value={form.eventSlug} required onChange={e=>{setForm({...form,eventSlug:e.target.value});setPrizes(rows=>rows.map(row=>({...row,eventSlug:e.target.value})));}}><option value="">Choose event</option>{events.map(e=><option key={e.slug} value={e.slug}>{e.title}</option>)}</select></label><div className="admin-field-grid"><label><span>Registration opens</span><input type="datetime-local" value={form.registrationOpensAt} onChange={e=>setForm({...form,registrationOpensAt:e.target.value})}/></label><label><span>Registration closes *</span><input type="datetime-local" required value={form.registrationClosesAt} onChange={e=>setForm({...form,registrationClosesAt:e.target.value})}/></label><label><span>Check-in closes</span><input type="datetime-local" value={form.checkInClosesAt} onChange={e=>setForm({...form,checkInClosesAt:e.target.value})}/></label><label><span>Tournament starts *</span><input type="datetime-local" required value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></label><label><span>Table size</span><select value={form.tableSize} onChange={e=>setForm({...form,tableSize:Number(e.target.value)})}><option value="9">9 max</option><option value="6">6 max</option></select></label><label><span>Starting stack</span><input type="number" min="100" value={form.startingStack} onChange={e=>setForm({...form,startingStack:Number(e.target.value)})}/></label></div><button className="btn btn-primary" disabled={busy}>Create tournament draft</button></form></div>
    {selectedRow&&detail&&<><section className="admin-surface admin-poker-status"><div className="admin-section-title"><div><span>Selected operation</span><h2>{selectedRow.title}</h2></div><em className="admin-status">{selectedRow.state.replaceAll('_',' ')}</em></div><div className="admin-poker-blockers">{selectedRow.publishBlockers.map(code=><span key={code}>{blockers[code]||code}</span>)}{!selectedRow.publishBlockers.length&&<b>Ready to publish</b>}</div><div className="admin-poker-actions"><button disabled={busy||selectedRow.state!=='draft'||selectedRow.publishBlockers.length>0} onClick={()=>lifecycle('publish','Tournament published.')}>Publish</button><button disabled={busy||selectedRow.state!=='scheduled'} onClick={()=>lifecycle('open-registration','Registration opened.')}>Open registration</button><button disabled={busy||selectedRow.state!=='registration_open'} onClick={()=>lifecycle('lock-registration','Registration locked.')}>Lock registration</button><button disabled={busy||!['registration_open','registration_locked'].includes(selectedRow.state)} onClick={()=>lifecycle('start','Tournament started.','Start and randomly seat all eligible players?')}>Start tournament</button><button disabled={busy||!['round_one','round_two','final_round'].includes(selectedRow.state)} onClick={()=>lifecycle('pause','Tournament paused.')}>Pause</button><button disabled={busy||selectedRow.state!=='paused'} onClick={()=>lifecycle('resume','Tournament resumed.')}>Resume</button><button className="danger" disabled={busy||['completed','cancelled','voided'].includes(selectedRow.state)} onClick={()=>lifecycle('cancel','Tournament cancelled.','Cancel this tournament and stop all tables?')}>Cancel</button></div></section>
      <div className="admin-two-column"><section className="admin-surface admin-form"><div className="admin-section-title"><div><span>Placements 1–3</span><h2>Prize package</h2></div></div>{prizes.map((p,i)=><div className="admin-poker-prize" key={p.placement}><b>0{p.placement}</b><label><span>Tier</span><input value={p.ticketTier} onChange={e=>setPrize(i,'ticketTier',e.target.value)}/></label><label><span>Tickets</span><input type="number" min="1" max="10" value={p.ticketQuantity} onChange={e=>setPrize(i,'ticketQuantity',Number(e.target.value))}/></label><label><span>Retail value</span><input type="number" min="0" value={p.approximateRetailValue} onChange={e=>setPrize(i,'approximateRetailValue',Number(e.target.value))}/></label></div>)}<button className="btn btn-primary" type="button" onClick={savePrizes} disabled={busy}>Save all three prizes</button></section>
      <section className="admin-surface admin-form"><div className="admin-section-title"><div><span>Immutable version</span><h2>Rules & legal review</h2></div></div><label><span>Complete official rules (EN)</span><textarea rows="12" minLength="400" value={rules.bodyMarkdown} onChange={e=>setRules({...rules,bodyMarkdown:e.target.value})} placeholder="Paste reviewer-approved rules. Placeholder content is rejected by the API."/></label><button type="button" className="btn btn-ghost" disabled={busy||rules.bodyMarkdown.length<400} onClick={()=>run(()=>api.adminPokerRules(selected,{locale:'en',bodyMarkdown:rules.bodyMarkdown,disclosures:{noPurchaseStatement:'No purchase necessary. Entry is free.',prizeDescription:'Event ticket prizes for placements 1, 2 and 3.'}}),'Official rules saved.')}>Save rules version</button><label><span>Legal reviewer name</span><input value={rules.reviewer} onChange={e=>setRules({...rules,reviewer:e.target.value})}/></label><button type="button" className="btn btn-primary" disabled={busy||rules.reviewer.trim().length<3||!detail.tournament.rulesVersion} onClick={()=>run(()=>api.adminPokerLegal(selected,{status:'approved',reviewer:rules.reviewer,note:'Approved for publication'}),'Legal approval recorded.')}>Record reviewer approval</button><p className="admin-form-note">This control records a human decision. It does not generate legal terms or replace legal advice.</p></section></div>
      <section className="admin-surface"><div className="admin-section-title"><div><span>Live operations</span><h2>Players, rounds & tables</h2></div><p>{detail.registrations.length} registrations</p></div><div className="admin-poker-metrics"><article><b>{detail.registrations.length}</b><span>registered</span></article><article><b>{detail.rounds.length}</b><span>rounds created</span></article><article><b>{detail.tables.length}</b><span>tables</span></article><article><b>{detail.liveTables.length}</b><span>live now</span></article></div><div className="admin-poker-audit">{detail.audit.slice(0,12).map(row=><article key={row._id}><time>{dt(row.at)}</time><b>{row.type.replaceAll('_',' ')}</b><span>{row.actor||'system'}{row.reason?` · ${row.reason}`:''}</span></article>)}</div></section></>}
  </div>;
}
